---
- name: Install Docker
  hosts: all # We need to docker all hosts
  become: true
  tags:
    - docker-init
  roles:
    - role: "nickjj.docker" # https://github.com/nickjj/ansible-docker
      docker__channel: [ "stable" ]
      docker__version: "25.0"
      docker__users:
        - "{{ ansible_user_id }}" # Root
        - "{{ ansible_user }}" # ssh user
  tasks:
    - name: Log into github private registry
      become_user: "{{ item }}"
      become: yes
      community.docker.docker_login:
        registry_url: ghcr.io
        GitKli22: "{{ vault_github_package_user }}"
        password: "{{ vault_github_package_password }}"
      loop:
        - "{{ ansible_user_id }}" # Root
        - "{{ ansible_user }}" # ssh user
      tags:
        - docker-login

    - name: Get the script allowing to wait for a docker stack deploy to complete
      vars: # https://github.com/sudo-bmitch/docker-stack-wait
        version: 5ae8405fd29b50b5c0a8df715e947ecf64897bff
      block:
        - name: Download the script from GitHub
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/sudo-bmitch/docker-stack-wait/{{ version }}/docker-stack-wait.sh
            dest: /usr/local/bin/docker-stack-wait
            mode: "0775"


- name: Install docker swarm on the manager
  hosts: ovh_manager
  become: true
  tasks:
    - name: Swarm
      vars:
        # We use the python interpreter created by the role nickjj.docker.
        # It contains the dependencies we need to init swarm
        ansible_python_interpreter: /usr/local/bin/python3-docker
      tags:
        - swarm
      block:
        - name: Init Swarm cluster address {{ ansible_default_ipv4.interface }}
          community.docker.docker_swarm:
            state: present
            advertise_addr: "{{ ansible_default_ipv4.interface }}"
            task_history_retention_limit: 5
          register: init_swarm_result

        - name: Swarm init result
          debug:
            msg: "{{ init_swarm_result }}"

        - name: Install docker_stack module requirements
          ansible.builtin.pip:
            name: "{{ item }}"
          loop:
            - jsondiff
            - pyyaml


# For multi hosts swarm: https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts
# sudo ufw allow in from 192.168.252.0/22 to any port 2377 proto tcp comment 'Swarm: TCP for communication with and between manager nodes'
# sudo ufw allow in from 192.168.252.0/22 to any port 7946 proto tcp comment 'Swarm: for overlay network node discovery tcp'
# sudo ufw allow in from 192.168.252.0/22 to any port 7946 proto udp comment 'Swarm: for overlay network node discovery udp'
# sudo ufw allow in from 192.168.252.0/22 to any port 4789 proto udp comment 'Swarm: for overlay network traffic'
