# See https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4:8.9
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_default_admin_email }}"
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/{{ pgadmin_default_admin_password_swarm_secret_name }}
    secrets:
      - "{{ pgadmin_default_admin_password_swarm_secret_name }}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - "{{ traefik_network }}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
      rollback_config:
        order: start-first
        parallelism: 1
      restart_policy:
        condition: any
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public

        # Http router: redirection to https
        - traefik.http.routers.pgadmin-http.rule=Host(`{{ pgadmin_domain }}`)
        - traefik.http.routers.pgadmin-http.entrypoints=http
        - traefik.http.routers.pgadmin-http.middlewares=https-redirect

        # Https router
        - traefik.http.routers.pgadmin-https.rule=Host(`{{ pgadmin_domain }}`)
        - traefik.http.routers.pgadmin-https.entrypoints=https
        - traefik.http.routers.pgadmin-https.tls=true
        - traefik.http.routers.pgadmin-https.tls.certresolver=letsencrypt

        - traefik.http.services.pgadmin.loadbalancer.server.port=80

secrets:
  "{{ pgadmin_default_admin_password_swarm_secret_name }}":
    external: true

volumes:
  pgadmin-data:

networks:
  "{{ traefik_network }}":
    external: true
